### ISSUE TITLE
Bike sharing option in the router seems to be not available

### ISSUE THREAD

**Issue by rcavaliere** [noi-techpark/odh-mentor-otp#117]
https://user-images.githubusercontent.com/9825179/144925880-08c7d762-d99c-437e-a368-402764a60acb.mp4

**Comment by zabuTNT** [comment]
Hi Roberto,
I already reported this on our fork: 
https://github.com/openmove/odh-mentor-otp/issues/111

If you open Advanced Settings, you will see that Bikesharing is selected, but it's not clear.
