### ISSUE TITLE
As a project manager I would like to adapt the application for the domain mobility.bz.it

### ISSUE THREAD

**Issue by rcavaliere** [noi-techpark/odh-mentor-otp#118]
We also host the domain https://mobility.bz.it/ It was actually the version of mobility.meran.eu but "adapted" for the Municipality of Bolzano. Our idea is to make something similar as for the Merano domain, i.e. if we access from this domain you get access to the same application but with some adaptations.
In particular:
- [ ]  attached logo to be visualized in the top left
- [ ] default starting position on the map: should be in the city centre of Bolzano, not Merano

![Citta_BZ](https://user-images.githubusercontent.com/9825179/145347490-0ec1bc76-6204-462a-a5d0-efaec25b6ed4.jpg)

**Comment by stefanocudini** [comment]
@rcavaliere for this domain confirm this logo?
![](https://mobility.bz.it/images/mobility.png)

**Comment by stefanocudini** [comment]
@rcavaliere should the above logo replace this?
![](https://mobility.bz.it/images/mobility.png)

**Comment by rcavaliere** [comment]
@stefanocudini yes exactly. Where is the page title displayed?

**Comment by stefanocudini** [comment]
at top left.
I'm slightly resizing the image logo for sizes limits

**Comment by stefanocudini** [comment]
this solved and included in PR #134 

to customize title for each domain, you can act here: in file /joruney/config.yml (any changes require a docker rebuild of journey)
https://github.com/noi-techpark/odh-mentor-otp/blob/8b8bd831add94614fcd490bbc7bfa61384a609c8/journey/config.yml#L26-L30
for example here the title is empty `''` and contains only logo

**Comment by rcavaliere** [comment]
However if I go to mobility.bz.it. I still get opened the old application. @RudiThoeni did we integrate this in the productive development and made a rebuild of the application?

**Comment by RudiThoeni** [comment]
hi rcavaliere, did not know about this.......
i have to redirect the domain to the new application, and deploy the latest PR to production currently it is only on dev? i always wait for your ok to deploy it on prod ;)

**Comment by rcavaliere** [comment]
@RudiThoeni should be this PR: https://github.com/noi-techpark/odh-mentor-otp/pull/134 @stefanocudini right?
If yes, please proceed. For the moment I won't put into production the travel times functionality (see PR https://github.com/noi-techpark/odh-mentor-otp/pull/135)

**Comment by RudiThoeni** [comment]
@rcavaliere yes i deployed PR134 on production and redirected mobility.bz.it, 
maybe the zoom level should be increased because the stops are visible when you zoom in one step....

**Comment by RudiThoeni** [comment]
Here i think there is a little bug 
https://github.com/noi-techpark/odh-mentor-otp/blob/master/journey/config.yml#L33
always the default title Merano is taken

**Comment by rcavaliere** [comment]
@RudiThoeni thanks, agree with your comment on the zoom level. But I don't know if this can be adapted for the different URLs... @stefanocudini can you provide a feedback on that?

**Comment by RudiThoeni** [comment]
yes it is here ;)

```
configByDomain: 
   mobility.bz.it: 
     map: 
       initLat: 46.492111111111 
       initLon: 11.333333333333 
       initZoom: 14 
```

**Comment by stefanocudini** [comment]
> maybe the zoom level should be increased because the stops are visible when you zoom in one step....

yes this behavior is intended to show the stops only when there is a sufficient zoom level otherwise they are too close

instead, the initial zoom for the mobility.bz.it domain can be adapted to ensure that stops are immediately visible

**Comment by stefanocudini** [comment]
> Here i think there is a little bug
> https://github.com/noi-techpark/odh-mentor-otp/blob/master/journey/config.yml#L33
> always the default title Merano is taken

@RudiThoeni  yes I noticed this little bug I have the solution are a few lines .... but from some branch can I send you a PR for this thing? our fork (development branch) now includes also the traffic layer.

if it is not an urgent thing I can include it together with the next PR which also includes changes on the traffic layer

**Comment by RudiThoeni** [comment]
the best is if this is inside the next PR with changes on traffic layer... otherwise we have a some confusion and we have to cherry pick commits to deploy etc....
@rcavaliere when are we ready to deploy also the traffic layer on production?

**Comment by stefanocudini** [comment]
about this I will add details under dedicated PR to the traffic layer #135
