### ISSUE TITLE
Http Referer on calls to ODH

### ISSUE THREAD

**Issue by RudiThoeni** [noi-techpark/odh-mentor-otp#129]
Hi 

We have a logging for all ODH calls where we group the calls by referer. I tested with http://journey.opendatahub.bz.it and i have seen that the http referer send to ODH is:

`json.output.referer | https://tourism.opendatahub.bz.it/api/ODHActivityPoi/?searchfilter=partsc&pagesize=5&language=de&poitype=447&active=true&fields=Id,Detail.de.Title,GpsInfo`

Strange that the whole call destination is sent as HTTP Header Referer..... Maybe the framework is doing it automatically...... the referer normally should be the webpage where the call starts......

Is it possible to set an explicit HTTP Referer Header which only passes the host from which the call is made ?at example (journey.opendatahub.bz.it, or mobility.meran.eu) that would be perfect so we can make advanced statistics / dashboards

thx and cheers
Rudi

**Comment by stefanocudini** [comment]
you are right!

**Comment by stefanocudini** [comment]
I don't understoodd, trying to replicate the problem but it doesn't seem to me that the client is sending anything other than hostname:
![image](https://user-images.githubusercontent.com/47107/146552947-1bff45cd-8da8-4388-8904-d0fb1745a404.png)
and in background the geocoder service only sends this http header to the ODH api:
`"User-Agent": "OpenMove-Geocoder-Client"`

**Comment by RudiThoeni** [comment]
very strange, i get the correct User-Agent in my logs but the referer is not right.....

![image](https://user-images.githubusercontent.com/30471361/146554640-46afe202-16fc-4142-9391-052c1c12a61a.png)

As you said The geocoder service does not pass the referer..... If it's not possible to fix/config on the geocoder side maybe i cann add a parameter which overwrites the header........

**Comment by RudiThoeni** [comment]
What i mean is the call to odh is made from `https://geocoder.otp.opendatahub.testingmachine.eu/v1/autocomplete?text=partschin&lang=&boundary.rect.min_lat=46.18828&boundary.rect.min_lon=10.470121&boundary.rect.max_lat=47.08878&boundary.rect.max_lon=12.255011`
the referer is passed from journey -> geocoder but not from geocoder --> odh.......... Is it possible to (re-)set it manually on geocoder backend? another option could be i add a parameter to the odh call which can be filled with the referer got from journey - geocoder ....... 
The interesting statistics for us would be to know if the user was on journey, or on mobility.meran etc.... what did he searched on odh etc..

**Comment by stefanocudini** [comment]
currently the geocoder service does not send any additional headers other than the user-agent.
I think it is the http proxy that appends these headers.

what comes out of the geocoder towards api or dh are the following headers:
```
GET /api/ODHActivityPoi/?searchfilter=cose&pagesize=5&language=en&poitype=447&active=true&fields=Id,Detail.en.Title,GpsInfo HTTP / 1.1
User-Agent: OpenMove-Geocoder-Client
host: localhost: 9090
content-length: 0
Connection: close

GET /api/Accommodation?searchfilter=hotel&pagesize=5&language=en&poitype=447&active=true&fields=Id,AccoDetail.en.Name,Latitude,Longitude HTTP / 1.1
User-Agent: OpenMove-Geocoder-Client
host: localhost: 9090
content-length: 0
Connection: close

GET /api/ODHActivityPoi/?searchfilter=hotel&pagesize=5&language=en&poitype=447&active=true&fields=Id,Detail.en.Title,GpsInfo HTTP / 1.1
User-Agent: OpenMove-Geocoder-Client
host: localhost: 9090
content-length: 0
Connection: close
```

To verify this I'm replaced odh endpoint with ```nc -l -k -p 9090``` in my local geocoder config.

**Comment by stefanocudini** [comment]
however we can config custom header in geocoder request here:
https://github.com/openmove/odh-mentor-otp/blob/master/geocoder/config.yml#L16

but I think that http proxy may be overwrite as it is currently doing

**Comment by RudiThoeni** [comment]
Sorry, I overlooked that the requests are done to /api/ . ODH here does a redirect to /v1/ so i think the referer is overwritten/set by the redirect ;)

We can try the following
Set the ODH Endpoints from `https://tourism.opendatahub.bz.it/api/ODHActivityPoi/` to
`https://tourism.opendatahub.bz.it/v1/ODHActivityPoi/`
and we set a manually a referer like "https://journey.opendatahub.bz.it/" and it should work!
When possible to set it by Environment variables would be perfect, so i can set another referer for testing + prod environment

thx and have a good weekend!

**Comment by RudiThoeni** [comment]
ok i set the ODH Endpoints to "v1" now no referer is passed
![image](https://user-images.githubusercontent.com/30471361/146609315-77812277-b36f-4d51-a64f-be7c2b170f32.png)

so let's set manually the referer header as environment variable next week

**Comment by stefanocudini** [comment]
I sent this PR that inslude Google Analytics integration #130 
I think you can also use this tool to track referrers

**Comment by RudiThoeni** [comment]
hi @stefanocudini any news about how to set this headers config?
thx

**Comment by stefanocudini** [comment]
@RudiThoeni send new PR about this here: https://github.com/noi-techpark/odh-mentor-otp/pull/132

**Comment by RudiThoeni** [comment]
thx!

**Comment by RudiThoeni** [comment]
working!
