### ISSUE TITLE
A.2.2 New OTP build with full GTFS

### ISSUE THREAD

**Issue by rcavaliere** [noi-techpark/odh-mentor-otp#14]
-  [x] Run new build with full GTFS

**Comment by rcavaliere** [comment]
Good news: we got today the full GTFS export, available here: https://cloud.opendatahub.bz.it/index.php/s/j9MpiMz3DEDwtgs
Let's discuss today how to organize the new OTP build

**Comment by bertolla** [comment]
I let the script go yesterday already I'm not sure the outcome is as expected. In any case I downloaded the logfile of the calculation if needed. See https://journey.opendatahub.testingmachine.eu/

**Comment by rcavaliere** [comment]
@bertolla I don't think that we are now seing the data provided by the new GTFS export... can you provide us some more details of the results you obtained at the end of the build?

**Comment by bertolla** [comment]
I took the zip file you uploaded ~111MB and replaced it(I renamed it to fit the original to avoid to change the pipeline) in the data folder. I run the calculations for the new Graph and according to the log files it got included for the calculations.

**Comment by rcavaliere** [comment]
@bertolla I am not sure that the client now shows the new GTFS export yet. @zabuTNT @stemove can you confirm this?
I would proceed in that way:
- [ ] successfully complete the build of the OTP graph (based on new GTFS export)
- [ ] integrate the new PR which integrates also the bike sharing data (GBFS feed)

**Comment by zabuTNT** [comment]
Hi @rcavaliere @bertolla ,
the graph is the old one, with old data. If you go here:
https://otp.opendatahub.testingmachine.eu/otp/routers/openmove/

you can see the build graph date: 
```<buildTime>1603729881302</buildTime>```
so: 26/10/2020

And again if you go here:
https://otp.opendatahub.testingmachine.eu/

you can plan a test travel from A to B (free to possible constrains of our webapp) , and you will see that there are no shapes in response.
![2020-11-09-104557_883x800_scrot](https://user-images.githubusercontent.com/5268372/98525459-c6b36e80-2278-11eb-805a-80f3a13342c1.png)

**Comment by bertolla** [comment]
I thought so, but I checked and the last graph in the data folder was created on 5. Nov. See:
![Screenshot from 2020-11-09 12-52-09](https://user-images.githubusercontent.com/3582457/98538162-a2f92400-228a-11eb-99f0-c90e74a628fd.png)

Maybe the small otp instance needs to restart to make it available or some other kind of trigger to use the new generated graph.

**Comment by bertolla** [comment]
I restarted the instance and now it's working. So I guess we need to trigger the loading in memory of the new graph to the live otp instance or we won't see when graph update.

**Comment by rcavaliere** [comment]
@bertolla nice, now it's seems to be the right GTFS file. But we stil don't see bikesharing data integrated, isn't @zabuTNT and @stemove?

**Comment by bertolla** [comment]
One step after another.
I'm doing it like this:
- [ ] make new graph file work
- [ ] trigger index update for 2nd otp instance
- [ ] adapt pipelines for new container
- [ ] deploy new version on test environment

**Comment by bertolla** [comment]
I guess we can trigger the reload by doing a simple put on this endpoint after graph calculation. I tried with curl, and it worked:
curl -i  -X PUT -H 'Content-Type:applicaton/json' "https://otp.opendatahub.testingmachine.eu/otp/routers/openmove"

**Comment by bertolla** [comment]
The bikesharing data is in another issue

**Comment by zabuTNT** [comment]
hi @bertolla,
don't use PUT in order to reload the graph. That open OTP to security issues. 

With the new pull request otp start with the **autoreload graph detector**, and without the possibility to use PUT/DELETE/POST for security reason.

So in the future you don't have to reload the graph manually.

**Comment by bertolla** [comment]
Nice didn't know about that. I will undo that change and redeploy. Thanks
