### ISSUE TITLE
As an end-user I would like that different on-demand services are visualized correctly on mobility.meran.eu

### ISSUE THREAD

**Issue by rcavaliere** [noi-techpark/odh-mentor-otp#166]
Current situation:

![Screenshot from 2023-07-31 11-58-56](https://github.com/noi-techpark/odh-mentor-otp/assets/9825179/97c1f804-388e-4a88-8fb6-5f7a6dc180cb)

- [x] It seems that the front-end recognizes two on-demand itineraries as one. Ideally we should see two separate paths.
- [x] We should avoid to visualize non real-time data like in Merano. Shall we put this data as non "non-active" in the DB? Let's do this once the first activity is done, so that in the future situation of different on-demand services in place the bug won't appear anymore.

**Comment by dulvui** [comment]
The on-demand itineraries are now shown independently and support multiple itineraries on testing:
https://journey.opendatahub.testingmachine.eu/#/

**Comment by dulvui** [comment]
@rcavaliere great! Now its live in production. I will check now how to hide data from Merano.

**Comment by dulvui** [comment]
@rcavaliere Merano data is now set to "active = false" and no longer visible on the map.
It's already active on production
