### ISSUE TITLE
A5 Multilingual front-end application

### ISSUE THREAD

**Issue by rcavaliere** [noi-techpark/odh-mentor-otp#17]
This user story covers the enhancement of the front-end application so that it is multilingual (content). Actually done; translations can be prepared and uploaded by NOI and should be easily configurable in the source code (e.g. through proper config files)

**Comment by stemove** [comment]
@rcavaliere 
I uploaded these two sample files in your cloud that you can use to produce the German translation
https://cloud.opendatahub.bz.it/index.php/s/MRsMxr8wkNW3Xpd?path=%2F
```language_en.js```
```language_it.js```

**Comment by rcavaliere** [comment]
@stemove @stefanocudini I have seen that EN and IT translations are already integrated in the source code. Why are they not always visible in the application, and the '$' are visualized instead of them? For example, I see the translations on Firefox, but not on Chrome

**Comment by rcavaliere** [comment]
@stefanocudini I have updated the DE JSON translation file and integrated the PR, but I can still not see the German update translations yet. Is there anything else to configure?

**Comment by stefanocudini** [comment]
only a rebuild of the journey image is required

**Comment by rcavaliere** [comment]
@bertolla can you please do it, so we can see the client available in 3 languages and close this issue?

**Comment by bertolla** [comment]
I did it and also the last pull request

**Comment by stefanocudini** [comment]
@rcavaliere 
About languages management in the latest version we have made some changes on the format of the files and their location.

Starting language is picked from browser, if the browser has a different language than the three defined, English is selected.

Now langs path is [here](https://github.com/openmove/odh-mentor-otp/tree/development/journey/app/lib/i18n):
```
journey/app/lib/i18n/
├── de.js
├── en.js
├── index.js
└── it.js
```
The application uses a fallback language defined in the `index.js` file currently set in English 'en'.

**Comment by rcavaliere** [comment]
@rcavaliere completes the additional translations according to the new languages management structure in this refactoring

**Comment by rcavaliere** [comment]
@stefanocudini translations updated in DE, IT and EN

**Comment by stefanocudini** [comment]
great! I'll do a quick check on this
