### ISSUE TITLE
As Open Data Hub manager I would like to have a first MVP of first end-user application based on the OTP React Redux open source project

### ISSUE THREAD

**Issue by rcavaliere** [noi-techpark/odh-mentor-otp#190]
https://github.com/opentripplanner/otp-react-redux

MVP = just connect the GraphQL API of the OTP instance v2 connected to the Open Data Hub and deploy it, with the current UI provided by this open source project

**Comment by rcavaliere** [comment]
Update: first MVP of the web-application shown.

Next steps:
- [ ] extend OSM data so to properly visualize flights -> @rcavaliere 
- [ ] manage Italian translations -> @rcavaliere 
- [ ] prepare 1st PR (decision: not fork but dependencies with OTP-UI and of OTP-RR) -> @ch-routerank

**Comment by ch-routerank** [comment]
Provided through #206

**Comment by clezag** [comment]
I've merged the PR, but the CI/CD for REUSE compliance was not set up correctly and so it didn't run for PRs.
Now we're missing license information for these files:
```
The following files have no copyright and licensing information:
* ../.gitmodules
* ../web-demo/.babelrc
* ../web-demo/.eslintrc.js
* ../web-demo/.gitignore
* ../web-demo/README.md
* ../web-demo/craco-icons.js
* ../web-demo/craco.config.js
* ../web-demo/lib/app/app.js
* ../web-demo/lib/app/components/example.js
* ../web-demo/lib/app/config.js
* ../web-demo/lib/app/example.css
* ../web-demo/lib/app/index.css
* ../web-demo/lib/app/index.js
* ../web-demo/lib/app/index.tpl.html
* ../web-demo/lib/app/main.js
* ../web-demo/lib/config.yml
* ../web-demo/yarn.lock
```
Not sure how to resolve this, as I have no insight into what comes from where or is original work

**Comment by ch-routerank** [comment]
Hello @rcavaliere we'll submit a PR addressing this tomorrow. While looking at it I saw that the reuse configuration doesn't seems correct for the current journey/ web app source folder (set as CC0 instead of MIT).

I'll address both points in my PR if fine for you.

**Comment by rcavaliere** [comment]
@ch-routerank we have deployed a first instance of the application on https://otp-react-redux.opendatahub.testingmachine.eu can you please check if there is everything you have currently implemented? It could be that some map layers implemented through a direct interface with the Open Data Hub API are not active, therefore please let us know.

cc @clezag @leonardehrenfried
