### ISSUE TITLE
`Authority` not assigned to `Line` with a `AuthorityRef`

### ISSUE THREAD

**Issue by leonardehrenfried** [noi-techpark/odh-mentor-otp#199]
Looking at https://cloud.opendatahub.com/index.php/s/dHXsK9KsFWdKXPC I see that the operators of the `Line`s are explicitly linked with a `OperatorRef`. The same is not true for `Authority`, which could be assigned with an `AuthorityRef`.

On the other hand, I note that the Authority is set as `FrameDefaults`:

```xml
     <FrameDefaults>
        <DefaultCodespaceRef ref="epip_data"></DefaultCodespaceRef>
        <DefaultResponsibilitySetRef ref="it:apb:Authority:apb:" version="any"></DefaultResponsibilitySetRef>
      </FrameDefaults>
```

Would you like to set the `AuthorityRef` explicitly (already supported) or change OTP code so that it parses the `FrameDefaults`?

cc @rcavaliere

**Comment by rcavaliere** [comment]
@leonardehrenfried I think we can consider the `FrameDefaults`, the `AuthorityRef` is always the same so it does not worth to insert it as additional field for all lines.
