### ISSUE TITLE
`ServiceJourneyPattern`s without `ServiceJourney`

### ISSUE THREAD

**Issue by leonardehrenfried** [noi-techpark/odh-mentor-otp#201]
There are a number of `ServiceJourneyPattern`s that are never referenced by a `ServiceJourney`.

It's possible that it's just harmless extra data that remains unused but could also indicate a larger error.

The full list of IDs is here: https://gist.github.com/leonardehrenfried/6dc0457d18cdf9e0409589f9fa542a62

**Comment by rcavaliere** [comment]
@leonardehrenfried I think this should not be considered as an issue. I explain you why.

Actually each line has different line versions. Typically each line version is characterized by a different `ServiceJourneyPattern`. The NeTEx exports are structured in this way: they are linked to an annual timetable, which is defined at the end of each year and enters into force each mid of December. When a new annual timetable is created, the first full NeTEx export generated contains all `ServiceJourney` of the year with associated `ServiceJourneyPattern`. Here typically you have all `ServiceJourneyPattern` associated to `ServiceJourney`. During the year however changes are applied, new `ServiceJourneyPatterns` are created, and associated to line versions, that could also have a limited period validity before considering the original pattern. When new exports are created, just the relevant `ServiceJourney` from the export date up to the end of validity of the annual timetable are exported. These means that `ServiceJourney` carried out in the past, i.e. from the start of the validity of the annual timetable up to the export date, are not exported any more. On the other side, this does not apply to `ServiceJourneyPattern`: in this case, all available `ServiceJourneyPattern` are always exported. This is the reason why you see such "inconsistency" in the data: some `ServiceJourneyPattern` could reference to `ServiceJourney` carried out in the past.

So, unless we have issues in the sense that there are ServiceJourney without referenced ServiceJourneyPattern, I I would not consider this an issue.
