### ISSUE TITLE
No real-time data on the journey details?

### ISSUE THREAD

**Issue by rcavaliere** [noi-techpark/odh-mentor-otp#25]
When I ask for the details of a journey with real-time data, I would expect to see the real-time travel times at the bus stops. Is it not here the case, see example?
![1](https://user-images.githubusercontent.com/9825179/107657626-9c14ef80-6c85-11eb-94f7-2f2feebf26a5.png)
![2](https://user-images.githubusercontent.com/9825179/107657633-9e774980-6c85-11eb-9da9-a794dff23695.png)

**Comment by zabuTNT** [comment]
Hi @rcavaliere 
if i remember, the real-time data are visible in the planned recap (first screenshot) and inside the details of the stop, not in the details of the trip (second screenshot). I will investigate about it.

**Comment by zabuTNT** [comment]
Hi @rcavaliere 
I confirm that you see realtime data only in the planned recap and in the stop detail. Maybe we can view about this in front-end future enhancements.

![2021-02-17-132048_641x561_scrot](https://user-images.githubusercontent.com/5268372/108203549-f77e2c00-7122-11eb-8af7-0c6f8eacf027.png)
