### ISSUE TITLE
Bike sharing data not anymore visible?

### ISSUE THREAD

**Issue by rcavaliere** [noi-techpark/odh-mentor-otp#27]
I remember that when I activate the layer, it was possible to see the data on the map... I can't also see any trip results with bike sharing, even in the case I want to plan a trip with this transport mode only.

Ok, this is why: https://gbfs.otp.opendatahub.testingmachine.eu/me/gbfs.json -> Service unavailable

**Comment by zabuTNT** [comment]
It seems that the gbfs server is down, 503 error.
https://gbfs.otp.opendatahub.testingmachine.eu/bz/1/gbfs.json
![2021-02-11-172527_1045x256_scrot](https://user-images.githubusercontent.com/5268372/107665856-295c4200-6c8e-11eb-977b-de3ad8e33b7d.png)

**Comment by bertolla** [comment]
I checked this, seems like the docker container was stopped. Maybe accidentally by me. It works again
