### ISSUE TITLE
A.2.1 OSM data import process

### ISSUE THREAD

**Issue by rcavaliere** [noi-techpark/odh-mentor-otp#3]

**Comment by stemove** [comment]
this is a list of companies that could offer osm data download services in a reliable way
https://wiki.openstreetmap.org/wiki/Commercial_OSM_Software_and_Services
what the project needs is an [Overpass server](https://wiki.openstreetmap.org/wiki/Overpass_API) that has the ability to provide data from a certain arbitrary boundingbox, currently our solution uses free servers

**Comment by stemove** [comment]
@bertolla 
I'm just uploaded a one file version of osm data here:
https://cloud.opendatahub.bz.it/index.php/s/MRsMxr8wkNW3Xpd?path=%2F
osm-all.tar.gz 294.3 MB
you can try to use it for building a new Graph.obj faster.
Uncompress it inside data directory and the other .osm files must be moved out of the given directory
In this way the creation time of the graph could be reduced.

**Comment by bertolla** [comment]
I did so. The graph calculation now takes around 7 minutes instead of ~ 10

**Comment by stemove** [comment]
Damn! I was hoping for less time :(
