### ISSUE TITLE
Shapes.txt:  too much precision

### ISSUE THREAD

**Issue by zabuTNT** [noi-techpark/odh-mentor-otp#35]
```
"46.1997476002557","11.1244785503585"
```

In the shapes.txt file there is too much precision: 13 decimals! 
This generate a big file, but, most of all, this has a huge impact on clients side when they draw the shapes on maps.

with 7 digits you have a precision of 0.0000001 degree,  so ~1cm.
with 13 digits, 0.0000000000001 degree, ~1nm !

**Comment by rcavaliere** [comment]
STA is not in the condition to change the export. Possible solutions: 

- processing of the GTFS export -> generation of new shapes.txt with simplified coordinates
- GTFS export is kept like this, data is properly handled and visualized by the end-user application

**Comment by rcavaliere** [comment]
Development probably not needed, the new version of the client can now properly show the shapes of the lines without any particular difficulty.

**Comment by rcavaliere** [comment]
@stefanocudini and @zabuTNT analyze if this is really needed...

**Comment by rcavaliere** [comment]
No more necessary
