### ISSUE TITLE
A.2.2/3 GTFS(-R) data availability preparation

### ISSUE THREAD

**Issue by rcavaliere** [noi-techpark/odh-mentor-otp#4]
- [x] STA will prepare us a full GTFS export with line geometries, multilingual names, etc. (by 23.10.2020)
- [x] STA (Mentz) is developing the GTFS-R which we can connect with (by Mid November)

@rcavaliere checks if also the notifications service is supported

**Comment by rcavaliere** [comment]
@bertolla 
First GTFS export to be tested is available here: https://cloud.opendatahub.bz.it/index.php/s/MRsMxr8wkNW3Xpd

**Comment by rcavaliere** [comment]
@rcavaliere will check quality of available GTFS through the OTP native front-end and will evaluate with STA the possibility to have a full GTFS exports with all planned data and geometry information included. In this case, a new build of the OTP instance has to be computed.

**Comment by stemove** [comment]
uploaded a first backup of OTP Graph based on gtfs above:
https://cloud.opendatahub.bz.it/index.php/s/MRsMxr8wkNW3Xpd
Graph-merano.backup.obj.gz

**Comment by rcavaliere** [comment]
Updates from STA: 
- [ ] STA will prepare us a full GTFS export with line geometries, multilingual names, etc.
- [ ] STA (Mentz) is developing the GTFS-R which we can connect with

**Comment by stemove** [comment]
@rcavaliere do you know which datasource they are extract line geometries?

**Comment by rcavaliere** [comment]
@stemove they do everything in DIVA
