### ISSUE TITLE
As an end-user I would like to see a "credits" button through which it is possible to see what the demonstrator is about, who has developed it, which are the partners, who has financed it, etc.

### ISSUE THREAD

**Issue by rcavaliere** [noi-techpark/odh-mentor-otp#65]
Should be similar to what currently implemented on mobility.meran.eu (see "About" - bottom right)

**Comment by rcavaliere** [comment]
First prototype available. JSON should be transformed in a HTML page so to manage both contents (multilingual) and images (logo), which should be same for the same languages and be available as common resources

**Comment by rcavaliere** [comment]
@stefanocudini the credits page looks good! 
Can you provide me some detail on how we can put content there (texts + logos)?

**Comment by stefanocudini** [comment]
@rcavaliere  now that you've merged the PR, I've made some simplifications in the code to make it easier to edits in the credits section.

in this position:
https://github.com/noi-techpark/odh-mentor-otp/blob/development/journey/app/lib/components/app/modal-credits.js#L23
you can insert html with links and logos.
Now it contains a basic structure that could be useful to follow to avoid mobile display problems.

to insert new logos, png / jpg files must be placed in this directory:
https://github.com/noi-techpark/odh-mentor-otp/tree/development/journey/app/lib/images/credits

and then inserted at the beginning of the credits file the references to the images as in the example comments here:
https://github.com/noi-techpark/odh-mentor-otp/blob/development/journey/app/lib/components/app/modal-credits.js#L8

**Comment by rcavaliere** [comment]
OK, now it's my turn to put contents here. Will let you know in case of problems.

**Comment by rcavaliere** [comment]
@stefanocudini I would like

**Comment by stefanocudini** [comment]
@rcavaliere 
after the <img> close tag </a> is required

I can fix this in the next PR.

**Comment by rcavaliere** [comment]
Ok, already seen. Thanks!
