### ISSUE TITLE
As an end-user I expect that the number in the icons of the map are related to clustering icons visualizing how many stations are present in that point, and not the available places / vehicles in a certain point

### ISSUE THREAD

**Issue by rcavaliere** [noi-techpark/odh-mentor-otp#71]
After some internal UX testing the current visualization on map is not optimal. Users seem to not understand that the number in the icon represent how many parking places / shared vehicles are currently available. We propose the following:
- [x] implement a clustering mechanism (see #48) with current number visualization in the icon
- [x] when each single station is visible use the red / yellow / green color associated to the icon so to immediately highlight the state of the station. Should be similar to current [mobility.meran.eu](https://mobility.meran.eu/) application. Following logic should be implemented: red = 0 availability; yellow = 1 availability (if availability > 1); green = 2 availability (if availability > 1) or 1 availability (if availability = 1)

**Comment by rcavaliere** [comment]
As said, wonderful work. Just complete the clustering mechanism for bikesharing and carsharing

**Comment by stefanocudini** [comment]
included in next PR https://github.com/noi-techpark/odh-mentor-otp/pull/83
