### ISSUE TITLE
"Printer" map seems to not work

### ISSUE THREAD

**Issue by rcavaliere** [noi-techpark/odh-mentor-otp#72]
Same problem with Firefox and Chrome. Also on mobile (iOS)

![Screenshot from 2021-07-29 06-52-13](https://user-images.githubusercontent.com/9825179/127433834-cc4f875a-5e5b-4c6c-a2e5-fbf6ab9f4585.png)

**Comment by zabuTNT** [comment]
It seems that stamen HTTPS certificate is wrong.

An alternative could be use not secure connection, or wait, maybe this will be resolved by their technicians.
http://tile.stamen.com/toner-lite/13/4350/2892.png

**Comment by stefanocudini** [comment]
just solved here: https://github.com/openmove/odh-mentor-otp/commit/67f5f2b744aca0252de79295f4db644f19707320
