### ISSUE TITLE
As an end-user I expect to have a more user-friendly when searching for an origin / destination

### ISSUE THREAD

**Issue by rcavaliere** [noi-techpark/odh-mentor-otp#75]
Having POIs suggestion is very good, but probably this is not sufficient for normal users. I think most users would try to insert a normal address, and they expect that this is somehow recognized and taken into account. Suggestion is to improve the geocoder so to resolve addresses by using an available free online service.
Tasks to be foreseen:
- [x] analysis of the available solutions and choice
- [x] implementation of the improvement 
- [x] HERE API key configuration by @rcavaliere 
- [x] trip planner search optimization (categories orders', number of results, categories' icons)

**Comment by rcavaliere** [comment]
To discuss during next meeting. Possibilities:
- Pelias (service for fee)
- HERE (evaluate freemium model)

**Comment by stefanocudini** [comment]
I'm testing the integration with HERE api for geocoding, these need to generate an appID and appCode related to the mentor instance, which you can generate by following this guide:
https://developer.here.com/tutorials/getting-here-credentials/#signing-up-and-getting-your-api-key

requests limits is here: https://developer.here.com/pricing

I'll make sure you can put the keys in new environment variables

**Comment by rcavaliere** [comment]
https://developer.here.com/pricing#plan-details

**Comment by stefanocudini** [comment]
about the fourth point of this issue, I solved the categorie's icons based on the search source data, I will post this in the next PR:
![geocoder_icons](https://user-images.githubusercontent.com/47107/132719906-ddb9bb6a-298b-444f-a8d3-498b00cf0ca9.png)

**Comment by Piiit** [comment]
@RudiThoeni FYI

**Comment by rcavaliere** [comment]
I have finally registered and created an APPID.
I have seen that it is not possible to create an APPCODE, see https://developer.here.com/documentation/identity-access-management/dev_guide/topics/dev-appcode.html 
I have instead created an APPKEY that we probably need to use.
@stefanocudini can you check if we need to adapt something since HERE does not support APPCODE anymore?
@RudiThoeni how should you pass these credentials in a secure way?

**Comment by rcavaliere** [comment]
@RudiThoeni in testing seems to work fine. Let's put this new version in production!

**Comment by RudiThoeni** [comment]
done
