### ISSUE TITLE
As an end-user I don't understand in the router setting if an option is active or not

### ISSUE THREAD

**Issue by rcavaliere** [noi-techpark/odh-mentor-otp#76]
See screenshot. A more visible
![llkbfemneelamleg](https://user-images.githubusercontent.com/9825179/127533432-0747ba02-878b-4d2f-bc99-8e5471477f51.png)
 color for highlighting is necessary...

**Comment by stefanocudini** [comment]
I hope this is clearer
![image](https://user-images.githubusercontent.com/47107/127624092-3c10ab09-6628-4d94-b35a-633d745bf877.png)

**Comment by rcavaliere** [comment]
@stefanocudini would be perfect!
