### ISSUE TITLE
As an end-user I expect to have different icons for the different options offered by the router

### ISSUE THREAD

**Issue by rcavaliere** [noi-techpark/odh-mentor-otp#78]
Currently it is not case, some icons are used multiple times.

**Comment by rcavaliere** [comment]
@stefanocudini I have seen the new icons, they are better but in my opinion not sufficient clear enough for a simple user. The single transport modes icones are OK, but I would improve and the intermodal options. My suggestion would be to go in this direction: alwasy the bus icon + the associated transport mode (see example attached). For park & ride I would use the 'P' icon while for car sharing and ride a car icon. We just need to think at a good icon solution to differentiate bike and bikesharing...
![Bild1](https://user-images.githubusercontent.com/9825179/129913955-e49d8070-ac8b-4fcc-912a-9a09d2797412.png)

**Comment by stefanocudini** [comment]
it's a good idea to associate bus icon in "... & Ride" modes.
For now, personal bike and bikesharing differ in the presence of the clock

**Comment by rcavaliere** [comment]
@stefanocudini yes I have seen. On mobility.meran.eu we used something that was quite understood, i.e. the double arrow on the transport mean meaning "sharing". Maybe we can go in this direction...
![marker](https://user-images.githubusercontent.com/9825179/129934509-14524c7d-ab36-45cc-8567-e83dc80c62cb.png)

**Comment by stefanocudini** [comment]
I will ask the UX colleagues for few icon sets for the modes

**Comment by rcavaliere** [comment]
New icons presented, to be included together with a mechanism to hide intermodal options. Please change the idea to click on the icon "bus" (not user friendly), please foresee a '+' or something like that gives immediately the hint to the users that there are other options to be activated.

https://user-images.githubusercontent.com/9825179/134698637-78792e28-d52e-447e-8464-290c978fe813.mp4

**Comment by rcavaliere** [comment]
@stefanocudini this looks very good. On mobile, however, I don't get currently all the options which are available. Please foresee something similar as for the presentation of the journeys' suggestions

![IMG_3276](https://user-images.githubusercontent.com/9825179/139710191-01df89d5-06ff-487c-b301-8b29542d16a7.PNG)

**Comment by stefanocudini** [comment]
maybe this is an unfortunate case of display size, all travel modes are available by swipe horizontally
![image](https://user-images.githubusercontent.com/47107/139821596-3c0bf221-2ac4-4e31-9bbe-612759b71553.png)

**Comment by stefanocudini** [comment]
probably the situation improves if I reduce the size of the buttons
