### ISSUE TITLE
As an EU officer I would like to see the Interreg Mentor logo on the application

### ISSUE THREAD

**Issue by rcavaliere** [noi-techpark/odh-mentor-otp#87]
Once the application goes online, we should have two different versions of the applications. The difference is just in the logo which replaces the word "MENTOR" in the top left corner:
- [x]  one available on mobility.meran.eu, with the logo "Merano" logo (see current application)
- [x] one available on a domain to be defined, which could be mentor.opendatahub.bz.it, with the logo Interreg (see attached)

![AsseIII_MENTOR](https://user-images.githubusercontent.com/9825179/132036536-a804e2d3-4187-4685-9ea5-51231dcd6c4d.png)

**Comment by stefanocudini** [comment]
@rcavaliere I have a question that is helpful for me to understand how to apply logo selection

these are two different deployments or
the same instance that is shown in two different domains?

**Comment by rcavaliere** [comment]
@stefanocudini I was asking myself the same question. At the end we just need two domains, not two different deployments. Can we do the second option while showing different logos in the two domains?

**Comment by stefanocudini** [comment]
yes exactly we can keep the same codebase and deployment and change the logo with the web domain.

I will try to make configurable

**Comment by stefanocudini** [comment]
![interreg_large](https://user-images.githubusercontent.com/47107/133228912-62580a9e-5ee8-4ae2-8048-82f278b5f905.png)
I think I will have to insert the modified logo in this way to avoid that the map layout (especially for mobile) is not compromised.

@rcavaliere would this be acceptable?

I have inserted their original instead in the credits section

**Comment by rcavaliere** [comment]
@stefanocudini let's try with this proposal!

**Comment by rcavaliere** [comment]
Functionality shown. Please integrate in the next PR!
