### ISSUE TITLE
As an end-user I would like to have a proper representation of bus stops on the maps, given the parent detail which is now available (simple solution)

### ISSUE THREAD

**Issue by rcavaliere** [noi-techpark/odh-mentor-otp#88]
Simple solution:
- [x] zoom out -> visualization of "father" bus stop"
- [x] zoom in -> visualization of "child" bus stop"

**Comment by rcavaliere** [comment]
See #89

**Comment by rcavaliere** [comment]
With the new version I see all the details of the bus stops at all zoom levels. This makes the application not usable at all. As agreed, the highest bus stop details should be visible only from a certain zoom level.

![IMG_3275](https://user-images.githubusercontent.com/9825179/139709281-bd7b5b94-174d-4827-8d1a-dee57ab5e9fe.PNG)

**Comment by stefanocudini** [comment]
@rcavaliere this is solved in the next PR:
https://github.com/noi-techpark/odh-mentor-otp/pull/99

**Comment by rcavaliere** [comment]
Tested, fine for me. Let's start closing tasks :-)
