### ISSUE TITLE
As a project manager I would like to bring the current OTP implementation in production

### ISSUE THREAD

**Issue by rcavaliere** [noi-techpark/odh-mentor-otp#90]
We need:
- [x] replicate front-end / back-end applications, so to have testing and production environment
- [x] testing applications should be left as they are. Productive applications should be reachable through other end-points (to be defined). End-user application should be accessible through mobility.meran.eu

**Comment by RudiThoeni** [comment]
@rcavaliere will contact Alex Lanz if he can replicate the testing environment on production

**Comment by RudiThoeni** [comment]
docker server api.mobility.docker.opendatahub.bz.it

**Comment by rcavaliere** [comment]
@alexlanz thanks for the update. Nobody of these end-points is the end-user application (OTP client), the end-point is https://journey.opendatahub.testingmachine.eu/ 
These end-points are API made at disposal by the OTP back-end that are used by the OTP client.
For the other question, yes, the values are to be kept as they are also for the productive environment

**Comment by RudiThoeni** [comment]
@rcavaliere We have a potential race condition. The application starts an AWS Instance to do some calculations and then stops it.
With the parameter GTFS_URL_UPDATETIME this updates are controlled (default:"daily" possible values: 15min|daily|hourly|monthly|weekly). We wanted to use the same Instance on Development & Production to do the calculations. The problem now is with this Scheduling possibilities the job is executed at the same time (even daily on production + weekly on test would lead to 1 day at week starting the instances at the same time), an and the AWS Instance is shut down by the faster service..... So it could occur the Instance is shut down during Calculations........

We wanted to ask if the developer can change this parameter GTFS_URL_UPDATETIME to a standardized cron schedule expressions so we can schedule Test + Production on different times?

**Comment by stefanocudini** [comment]
> otp_1 | 12:41:37.710 ERROR (GenericJsonBikeRentalDataSource.java:97) [severity: ALL_STATIONS] Failed to get data from url http://gbfs.otp.opendatahub.bz.it/bz/1/station_information.json (url: http://gbfs.otp.opendatahub.bz.it/bz/1/station_information.json)

I can suppose that Java don't support http redirect to https.. you can try use same url with **https**.
or it might depend on your container network configuration.
I can open the resource from remote and the data they see are correct

**Comment by RudiThoeni** [comment]
we did not found where we have defined a "http" link because on the config we set the https link GBFS_HOST ="https://gbfs.otp.opendatahub.bz.it/
so the question is where the http link comes from?

**Comment by RudiThoeni** [comment]
hera a full log when the container start
[containerlog.txt](https://github.com/noi-techpark/odh-mentor-otp/files/7474371/containerlog.txt)
s

**Comment by stefanocudini** [comment]
@RudiThoeni the problem is here: https://gbfs.otp.opendatahub.bz.it/bz/1/gbfs.json
it should list the url with the same protocol seen from the outside (but I think your proxy redirect http -> https breaks these requests)

we are trying to modify from code container.
About this I ask you if currently the proxy is also forwarding the protocol, in this way (example with nginx)
```
        proxy_next_upstream error timeout;
        proxy_pass http://localhost:8089;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forward-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forward-Proto https;
        proxy_set_header X-Nginx-Proxy true;
        proxy_redirect off;
        add_header X-Frame-Options "deny";
```
we need of X-Forward-Proto passed to service

**Comment by RudiThoeni** [comment]
since we use our new proxy (caddy) i read in the documentation that it should pass x-forward-proto by default, we have to check and if it does not it we will set it....
