### ISSUE TITLE
As an end-user I would like to have a settings filter associated with the layers "E-Charger" and "Carsharing"

### ISSUE THREAD

**Issue by rcavaliere** [noi-techpark/odh-mentor-otp#91]
As proposed in the UX / UI design of #78 
The filters should have the same fields as currently available on mobility.meran.eu

**Comment by rcavaliere** [comment]
@stefanocudini the filter looks very nice! However all the available options on car sharing are very strange, I would expect as models "Golf", "Caddy", etc. and not all the different models details. What are you using there to consider the different vehicles' models?

**Comment by stefanocudini** [comment]
hi @rcavaliere the problem is at the root in the api ODH cars models are not homogeneous and it is very difficult to write rules to group them:
https://mobility.api.opendatahub.bz.it/v2/flat%2Cnode/CarsharingCar?distinct=true&limit=500
look at **sname** field, this is the set of values:
```
VW Golf Golf A7 1.6 TDI Comf BMT
VW up! Move 1.0
VW Golf Variant 1.6 TDI comf 8MT
VW up! MOVE UP 1.0 60CV
VW up!
VW Golf GOLF A7 1.6TDI
VW up! VW up!
VW Golf VW Golf
VW Golf
VW Golf Golf 1.6 TDI
VW Caddy 1.6 TDI Trendline - 7 Sitzer ohne Stauraum
VW Caddy Caddy 2.0 TDI
Renault Zoe
VW ID.3 VW ID.3 PRO 58kWh
VW e-Golf
VW e-UP!
Nissan Leaf
```

**Comment by rcavaliere** [comment]
@stefanocudini you should consider smetadata -> brand. In this way we obtain the desired result. Can you fix this?

**Comment by rcavaliere** [comment]
@stefanocudini wonderful, now it works as expected. I have seen that there a couple of strings to be translated, I can do this.
